name: Gradle build
run-name: Gradle build (run name)
on: [push]
jobs:
  Gradle-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@HEAD
      - run: gradle build